channels:
  - conda-forge
  - defaults

dependencies:
  - bs4
  - dash
  - dash-bootstrap-components
  - dash-mantine-components
  - dill
  - jsonmerge
  - mat4py
  - moorpy==1.2.1
  - nlopt
  - numpydoc
  - numpy
  - openfast==4.2
  - openfast-io==4.2
  - pyopenfast==4.2
  - openraft>=2.0.3
  - openmdao
  - osqp
  - pcrunch>=2.1.5
  - pip
  - pygmsh==7.1.17 #(v) for 02_eg/hybrid_model example
  - pyhams>=1.3
  - pyvista
  #- pyoptsparse
  - pyvista
  - rosco>=2.10.1
  - trimesh
  - wisdem>=4.2
  - pip:
    - control
    - dash-vtk
    - dearpygui
    - smt
    # - git+https://github.com/NLRWindSystems/RAFT.git@dev
    # - git+https://github.com/LHEEA/meshmagick/archive/refs/tags/3.4.zip #(v) for 02_eg/hybrid_model example
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
